version: "3"

services:
  application:
    image: student-app-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    ports:
     - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tharunsk4
      - MYSQL_DATABASE=docker_db
    volumes:
      - /data/mysql
networks:
  springboot-db-net:
